name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

# TODO(bwplotka): Add tests here.
jobs:
  lint:
    runs-on: shopify-ubuntu-latest-2
    name: Linters (Static Analysis) for Go
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.21.x

      - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Format.
        run: make format

      - name: Linting & vetting
        run: make go-lint

  e2e:
    strategy:
      fail-fast: false
      matrix:
        parallelism: [10]
        index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    runs-on: shopify-ubuntu-latest-2
    name: Thanos end-to-end tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Go.
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.21.x

      - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests
        run: make test-e2e GH_PARALLEL=${{ matrix.parallelism }} GH_INDEX=${{ matrix.index }}

  unit:
    runs-on: shopify-ubuntu-latest-2
    name: Thanos unit tests
    env:
      THANOS_TEST_OBJSTORE_SKIP: GCS,S3,AZURE,SWIFT,COS,ALIYUNOSS,BOS,OCI,OBS
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Go.
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.21
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Run unit tests (without e2e tests against all real store buckets)
        run: make test
