name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

# TODO(bwplotka): Add tests here.
jobs:
  lint:
    runs-on: shopify-ubuntu-latest-2
    name: Linters (Static Analysis) for Go
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Format.
        run: make format

      - name: Linting & vetting
        run: make go-lint

  e2e:
    strategy:
      fail-fast: false
      matrix:
        parallelism: [4]
        index: [0, 1, 2, 3]
    runs-on: shopify-ubuntu-latest-2
    name: Thanos end-to-end tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go.
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests
        run: make test-e2e GH_PARALLEL=${{ matrix.parallelism }} GH_INDEX=${{ matrix.index }}

  unit:
    runs-on: shopify-ubuntu-latest-2
    name: Thanos unit tests
    env:
      THANOS_TEST_OBJSTORE_SKIP: GCS,S3,AZURE,SWIFT,COS,ALIYUNOSS,BOS,OCI,OBS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go.
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run unit tests (without e2e tests against all real store buckets)
        run: make test
