name: mixin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: shopify-ubuntu-latest-2
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.21.x

      - name: Generate
        run: make examples

      - name: Check
        run: make check-examples

  lint:
    runs-on: shopify-ubuntu-latest-2
    name: Linters (Static Analysis) for Jsonnet (mixin)
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.21.x

      - name: Format
        run: |
          make jsonnet-format
          git diff --exit-code

      - name: Linting
        run: make jsonnet-lint
