name: react

on:
  push:
    branches:
      - main
  pull_request:

permissions:  
  contents: read

jobs:
  build:
    runs-on: shopify-ubuntu-latest-2
    strategy:
      matrix:
        node: [ '14' ]
    name: React UI test on Node ${{ matrix.node }}
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install nodejs
        uses: shop/setup-javascript-action@main
        with:
          node-version: ${{ matrix.node }}
          pnpm-version: '7.33.7'

      - run: pnpm install --frozen-lockfile
        working-directory: pkg/ui/react-app

      - run: CI=false make check-react-app
      - run: make react-app-test
